apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260610-155150-2p529sa4f4zi-service
spec:
  selector:
    app: enterprise-system-20260610-155150-2p529sa4f4zi
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
